# ¡Bienvenidos a la última sesión de la semana 2 del Mastery Data Science!

## *Sesión de retos*

### Objetivo de la Sesión 3:

* Repasar NumPy resolviendo algunos ejercicios.
* Repasar Pandas resolviendo algunos ejercicios.
* Explorar el *set* de datos de la iniciativa 3de3.
* Elegir un reto y proponer una solución.
* Compartir lo que lograron en este día.

### *“Trabajar en equipo, divide el trabajo y multiplica los resultados”*, Anónimo.


####Agenda

9:00 a 10:00
* Repasar NumPy resolviendo algunos ejercicios.
* Repasar Pandas resolviendo algunos ejercicios.

10:00 a 10:20
* Ver soluciones de cada uno de los ejercicios.

10:20 a 11:00
* Explorar el *set* de datos de Titanic.

11:00 a 11:20
* Comentar resultados obtenidos de la exploración.

11:20 a 12:00
* Explorar el *set* de datos de la iniciativa 3de3.

12:00 a 13:00
* ¿Comer?

13:00 - 13:20
* Comentar resultados obtenidos de solución.

13:20 a 14:20
* Elegir un reto y proponer una solución.

14:20 a 14:40
* Presentar solución propuesta a reto.

14:40 - 15:00
* Compartir lo que lograron en este día.

In [1]:
import numpy as np
import pandas as pd

# 1. NumPy

1. Muestra la versión de NumPy utilizada

In [4]:
np.version.version

'1.17.2'

2. Crear un arreglo 1D con enteros positivos aleatorios

In [21]:
m_array = np.random.randint(1,1000,size=10)
print(m_array)

[515  24 546  83 663 438 815 955 623 408]


3. Crear un arreglo booleano

In [41]:
arr_1 = np.random.randint(-10, 10,18)
arr_bool = np.array(arr_1,dtype=bool)
len(arr_bool)

18

4. Extraer los items que sean divisibles en 3.

In [22]:
m_filter = m_array % 3 == 0
m_array[m_filter]

array([ 24, 546, 663, 438, 408])

5. Convierte el arreglo booleano de 1D a 2D con tres filas (*reshape*)

In [43]:
type(arr_bool)
reshape_bool =  arr_bool.reshape(3,6)
reshape_bool

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

6. Obtén los items comunes entre dos arreglos

In [52]:
arr1 = np.array([2,3,4,5,6,7,10,20]) 
arr2 = np.array([12,3,4,5,90])

set_arr1 = np.unique(arr1)
set_arr2 = np.unique(arr2)

np.intersect1d(arr1, arr2)


array([3, 4, 5])

7. Extrae los números del vector creado en el ejercicio 2 que esten a dos números de distancia del valor promedio del arreglo.

In [76]:
m_mean = m_array.mean()
limit_1 = m_mean + 100
limit_2 = m_mean - 100
print (limit_1)
print(limit_2)
print(m_array)
#m_filter = m_array >= limit_2 and m_array <= limit_1
result = np.where((m_array >= limit_2) & (m_array <= limit_1))
m_array[result]

607.0
407.0
[515  24 546  83 663 438 815 955 623 408]


array([515, 546, 438, 408])

8. Muestra solo 3 decimales en un vector.

In [77]:
np.random.random(3)

array([0.16146736, 0.8554319 , 0.02907842])

9. Crea una atriz de 3x3 con los valores del 0 a 8

In [85]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Del siguiente areglo [1,2,0,0,4,] encuentra los índices donde los elementos sean diferente a cero.

In [87]:
a_array = np.array([ 1,2,0,0,4])
np.where(a_array != 0)

(array([0, 1, 4]),)

11. Crea un vector aleatorio de 30 elementos y encuentra la media.

In [88]:
m_vector = np.random.randint(1,100,30)
m_vector.mean()

46.7

12. Crea un arreglo 2D con 1 en los bordes y 0 dentro. Por ejemplo:
1 1 1 1 1
1 0 0 0 1
1 0 0 0 1
1 1 1 1 1

13. ¿Cuál es el resultado de la siguiente expresión?

`0 * np.nan`

`np.nan == np.nan`

`np.inf > np.nan`

`np.nan - np.nan`

`np.nan in set([np.nan])`

`0.3 == 3 * 0.1`


14. Crea una matriz de 5x5 con valores 1, 2, 3, 4 justo después de la diagonal.

15. Normaliza una matriz aleatoria de 5x5

# 2. Pandas

1. Imprime toda la información de versión de las librerias que necesita la biblioteca de pangas.

In [99]:
import pandas as pd
pd.__version__

'0.25.1'

Considera el siguiente diccionario y lista.


```
data = {
     'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
     'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
     'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
     'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

2. Crea un DataFrame con el diccionario *data* que tenga como índices los valores de la lista *labels*.

In [135]:
data = {
     'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
     'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
     'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
     'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

m_df = pd.DataFrame(data)
m_df.index = labels
m_df


animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

3. Muestra una descripción o información básica acerca del DataFrame y sus datos. (Pista: existe una función que lo muestra).

In [145]:
m_df.shape
m_df.describe()

Edad    Visitas
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

4. Regresa las primeras 3 filas del DataFrame

In [109]:
m_df.head(3)

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

5. Cambia el nombre de las columnas por:


*   Animal
*   Edad
*   Visitas
*   Prioridad



In [137]:
m_df.columns = ["Animal" , "Edad" , "Visitas", "Prioridad"]
m_df

Animal  Edad  Visitas Prioridad
a    cat   2.5        1       yes
b    cat   3.0        3       yes
c  snake   0.5        2        no
d    dog   NaN        3       yes
e    dog   5.0        2        no
f    cat   2.0        3        no
g  snake   4.5        1        no
h    cat   NaN        1       yes
i    dog   7.0        2        no
j    dog   3.0        1        no

6. Muestra solo la columna "animal" and "age". ¿Esto es posible? Si no es posible, ¿qué debería ser?

In [111]:
m_df[['Animal', 'Edad']]

Animal  Edad
a    cat   2.5
b    cat   3.0
c  snake   0.5
d    dog   NaN
e    dog   5.0
f    cat   2.0
g  snake   4.5
h    cat   NaN
i    dog   7.0
j    dog   3.0

7. Selecciona solo las filas donde el número de visitas sea mayor que 3.

In [113]:
m_df[m_df['Visitas'] >= 3]

Animal  Edad  Visitas Prioridad
b    cat   3.0        3       yes
d    dog   NaN        3       yes
f    cat   2.0        3        no

8. ¿Cuáles son las filas donde la edad es NaN?

In [147]:
m_df[m_df['Edad'].isnull()]

Animal  Edad  Visitas  Prioridad
d    dog   NaN        3       True
h    cat   NaN        1       True

9. ¿Qué animales tienen una edad entre 2 y 4 años?

In [119]:
m_df[(m_df['Edad'] >= 2) & (m_df['Edad'] <= 4)]

Animal  Edad  Visitas Prioridad
a    cat   2.5        1       yes
b    cat   3.0        3       yes
f    cat   2.0        3        no
j    dog   3.0        1        no

10. ¿Cuál es el total de todas las visitas?

In [121]:
m_df['Visitas'].sum()

19

12. Tenemos diferentes animales, ¿cuál es el número total de cada tipo de animal?

In [129]:
len(m_df['Animal'].unique())


3

13. Cambia los valores de la columna Prioridad por valores booleanos, es decir:
'yes' => True 
'no' => False

In [138]:
def transform_Prior(prioridad):
    result = False
    print(f'prioridad {prioridad}')
    if prioridad == 'yes':
        result = True
    return result
m_df['Prioridad'] = m_df['Prioridad'].apply(transform_Prior)
m_df

prioridad yes
prioridad yes
prioridad no
prioridad yes
prioridad no
prioridad no
prioridad no
prioridad yes
prioridad no
prioridad no


Animal  Edad  Visitas  Prioridad
a    cat   2.5        1       True
b    cat   3.0        3       True
c  snake   0.5        2      False
d    dog   NaN        3       True
e    dog   5.0        2      False
f    cat   2.0        3      False
g  snake   4.5        1      False
h    cat   NaN        1       True
i    dog   7.0        2      False
j    dog   3.0        1      False

14. Ordena el DataFrame por la Edad en orden descendiente y después por la columna Visitas en orden ascendente.

In [140]:
m_df.sort_values(['Edad', 'Visitas'], ascending = [False,True])

Animal  Edad  Visitas  Prioridad
i    dog   7.0        2      False
e    dog   5.0        2      False
g  snake   4.5        1      False
j    dog   3.0        1      False
b    cat   3.0        3       True
a    cat   2.5        1       True
f    cat   2.0        3      False
c  snake   0.5        2      False
h    cat   NaN        1       True
d    dog   NaN        3       True

15. Para cada tipo de animal y cada número de visitas encuentra la edad promedio. 
(Pista: Si haz utilizado tablas pivotes, cada fila es un animal, cada columna es el número de visitas y los valores son la media de la edad).

In [144]:
m_group = m_df.groupby(['Animal', 'Visitas'])
m_group.first()

Edad  Prioridad
Animal Visitas                 
cat    1         2.5       True
       3         3.0       True
dog    1         3.0      False
       2         5.0      False
       3         NaN       True
snake  1         4.5      False
       2         0.5      False

# 3. Introducción a un set de datos reales Iniciativa #3de3


Bajar el set de datos la iniciativa #3de3

Descargar información de https://www.3de3.mx/datos_abiertos

In [148]:
import requests
import pandas as pd

declarantes_json = requests.get("https://3de3.mx/declarantes.json?by_gender=F&page=1&by_political_party=PAN")
declarantes = pd.DataFrame(declarantes_json.json())
declarantes

id           first_name              last_name          twitter  \
0   4918       Martha Cecilia       Márquez Alvarado   mmarthamarquez   
1   4929      Alejandra Noemí        Reynoso Sánchez      WeraReynoso   
2   4933             Verónica      Delgadillo García  VeroDelgadilloG   
3   4944        Mayuli Latifa         Martínez Simón   MayuliMtzSimon   
4   4953              Minerva        Hernández Ramos    MinervaHdezMX   
5   7031       Bertha Xóchitl            Gálvez Ruiz    XochitlGalvez   
6   4909      Indira de Jesús      Rosales San Román        Indira_rs   
7   4907     Josefina Eugenia           Vázquez Mota       JosefinaVM   
8   5055         Martha Elisa       González Estrada     MarthaGlzAgs   
9   5072               Mónica          Almeida López  MonicaAlmeidalo   
10  5080            Ana Paola          López Birlain     PANqueretaro   
11  5078                Sonia           Rocha Acosta         SonRocha   
12  5081             Josefina           Salazar Baez      JosefinaSLP   
13  5084     Mariana Dunyaska           García Rojas   DunyaskaPANVer   
14  5044              Adriana       Dávila Fernández   AdrianaDavilaF   
15  7033  Cecilia Anunciación         Patrón Laviada   CeciliaPatronL   
16  5049       Laura Angélica        Rojas Hernández     Laura_Rojas_   
17  5050               Gloria            Romero León   AccionNacional   
18  5036             Patricia          Terrazas Baca   AccionNacional   
19  5039        María Marcela        Torres Peimbert    Marce_Torres7   
20  7066         María Teresa       Jiménez Esquivel     TereJimenezE   
21   837        Mirna Cecilia          Rincón Vargas     MirnaRincon1   
22  6395        María Eugenia          Campos Galván     MaruCampos_G   
23  6496               Elvira     Paniagua Rodríguez   Elvira_PaniRod   
24  6457               Marina          Ponce Camacho     PANqueretaro   
25  6458        Ma. Guadalupe  Alcántara De Santiago       LSanatiago   
26  6478          Maki Esther        Ortiz Domínguez       MakiOrtizD   
27  6059    Claudia Guadalupe        De Lira Beltrán    Lupita_DeLira   
28  6056        Karina Ivette         Eudave Delgado     karinaeudave   
29  6061       Paloma Cecilia      Amezquita Carreón    PANAGSOFICIAL   
30  7043       María Trinidad            Vaca Chacón     PANBCSigamos   
31  7042            Eva Maria      Vásquez Hernández     PANBCSigamos   
32  5582             Marisela         Terrazas Muñoz    pan_chihuahua   
33   694        Blanca Amelia        Gámez Gutiérrez     BlancaGamezG   
34  5990    América Alejandra       Rangel Lorenzana            PANDF   

            position                                          interests  \
0            Senador  {'document_link': 'https://s3-us-west-1.amazon...   
1            Senador  {'document_link': 'https://s3-us-west-1.amazon...   
2            Senador  {'document_link': 'https://s3-us-west-1.amazon...   
3            Senador  {'document_link': 'https://s3-us-west-1.amazon...   
4            Senador  {'document_link': 'https://s3-us-west-1.amazon...   
5            Senador  {'document_link': 'https://s3-us-west-1.amazon...   
6            Senador  {'document_link': 'https://s3-us-west-1.amazon...   
7            Senador  {'document_link': 'https://s3-us-west-1.amazon...   
8   Diputado federal  {'document_link': 'https://s3-us-west-1.amazon...   
9   Diputado federal  {'document_link': 'https://s3-us-west-1.amazon...   
10  Diputado federal  {'document_link': 'https://s3-us-west-1.amazon...   
11  Diputado federal  {'document_link': 'https://s3-us-west-1.amazon...   
12  Diputado federal  {'document_link': 'https://s3-us-west-1.amazon...   
13  Diputado federal  {'document_link': 'https://s3-us-west-1.amazon...   
14  Diputado federal  {'document_link': 'https://s3-us-west-1.amazon...   
15  Diputado federal  {'document_link': 'https://s3-us-west-1.amazon...   
16  Diputado federal  {'document_link': 'https://s3-us-west-1.amazon...   
17  Diputado federal  {'doc

In [169]:
declarantes['genre'] = ''
declarantes

id         first_name              last_name          twitter  \
0    730     Kehila Abigail           Ku Escalante         kukehila   
1   6907     Mara Nadiezdha      Robles Villaseñor      MaraRoblesV   
2   5363      Mario Alberto     Rodríguez Carrillo     marioarguezc   
3   5069        Juan Carlos     Villarreal Salazar  SoyJCVillarreal   
4   5071   Adriana Gabriela           Medina Ortiz   DipCiudadanoMX   
5   5074     Arturo Roberto        Hernández Tapia   Partido_Morena   
6   6909  Xóchitl Nashielly          Zagal Ramírez     XochitlZagal   
7   5075    Ernesto Alfonso           Robledo Leal  ponchorobledomx   
8   5076     Ángel Benjamín         Robles Montoya  BenjaminRoblesM   
9   5077     José Guillermo    Aréchiga Santamaría       garechigas   
10  5080          Ana Paola          López Birlain     PANqueretaro   
11  5079    Felipe Fernando          Macías Olvera     PANqueretaro   
12  5078              Sonia           Rocha Acosta         SonRocha   
13  5081           Josefina           Salazar Baez      JosefinaSLP   
14  7004       Nancy Yadira        Santiago Marcos  YadiraMarcosSin   
15  5082        María Wendy        Briceño Zuloaga   Partido_Morena   
16  7146      Mario Alberto            Ramos Tamez    MarioRamosTam   
17  6560      José Salvador      Rosas Quintanilla     chavarosasmx   
18  5083             Lorena       Cuellar Cisneros    LorenaCuellar   
19  5084   Mariana Dunyaska           García Rojas   DunyaskaPANVer   
20  5085        Flora Tania            Cruz Santos  TaniaCr24432457   
21  5086         Jose Elías          Lixa Abimerhi        eliaslixa   
22  5038             Marcos           Aguilar Vega    MarcosAguilar   
23   751              María  Alemán Muñoz Castillo     MariaAlemanM   
24  5040     Ivonne Liliana         Álvarez García   alvarez_ivonne   
25  6620  Itzcóatl Tonatiuh          Bravo Padilla   MovCiudadanoMX   
26  6898       Jacobo David           Cheja Alfaro     Jacobo_Cheja   
27  5088            Tatiana     Clouthier Carrillo     tatclouthier   
28  5044            Adriana       Dávila Fernández   AdrianaDavilaF   
29  6912   Jorge Alcibíades            García Lara    J_GrciaLaraMX   
30  5051          Ana Lilia        Herrera Anzaldo  AnaLiliaHerrera   
31  5037        Juan Carlos       Loera De la Rosa       JloeraJuan   
32  6547    María del Pilar      Lozano Mac Donald    Pilarlozanomd   
33  6759     Carmen Julieta          Macías Rábago   JulietaMRabago   
34  5093     José Rigoberto          Mares Aguilar        RigoMares   

            position                                          interests  \
0   Diputado federal  {'document_link': 'https://s3-us-west-1.amazon...   
1   Diputado federal  {'document_link': 'https://s3-us-west-1.amazon...   
2   Diputado federal  {'document_link': 'https://s3-us-west-1.amazon...   
3   Diputado federal  {'document_link': 'https://s3-us-west-1.amazon...   
4   Diputado federal  {'document_link': 'https://s3-us-west-1.amazon...   
5   Diputado federal  {'document_link': 'https://s3-us-west-1.amazon...   
6   Diputado federal  {'document_link': 'https://s3-us-west-1.amazon...   
7   Diputado federal  {'document_link': 'https://s3-us-west-1.amazon...   
8   Diputado federal  {'document_link': 'https://s3-us-west-1.amazon...   
9   Diputado federal  {'document_link': 'https://s3-us-west-1.amazon...   
10  Diputado federal  {'document_link': 'https://s3-us-west-1.amazon...   
11  Diputado federal  {'document_link': 'https://s3-us-west-1.amazon...   
12  Diputado federal  {'document_link': 'https://s3-us-west-1.amazon...   
13  Diputado federal  {'document_link': 'https://s3-us-west-1.amazon...   
14  Diputado federal  {'document_link': 'https://s3-us-west-1.amazon...   
15  Diputado federal  {'document_link': 'https://s3-us-west-1.amazon...   
16  Diputado federal  {'document_link': 'https://s3-us-west-1.amazon...   
17  Diputado federal  {'document_link': 'https://s3-us-west-1.amazon...   
18  Diputado federal  {'

In [150]:
requests.get("https://3de3.mx/declarantes.json").json

<bound method Response.json of <Response [200]>>

1. Descargar las primeras 4 páginas
2. Agregar columna de género
3. Agregar columna de entidad

In [290]:
import json
import time

#m_df = pd.DataFrame(declarantes_json.json())
political_parties = ['PRI']
#['PRI', 'PAN', 'PT', 'PVEM', 'PRD', 'MC', 'Nueva Alianza', 'Morena', 'PH', 'PES']
all_genres = ['M','F']
all_pages = [1,2,3,4]
all_requests = np.array(np.meshgrid(all_genres,all_pages,political_parties)).T.reshape(8,3)
print(all_requests)
df_genre_party = pd.DataFrame()
ls_genre_party = []
df_total = pd.DataFrame()
for a_request in all_requests:
    a_genre = a_request[0]
    a_page = int(a_request[1])
    a_political_party = a_request[2]
    endpoint_req = f'https://3de3.mx/declarantes.json?page={a_page}&by_gender={a_genre}&by_political_party={a_political_party}'
    m_secs = np.random.randint(2,8, size=1)[0]
    time.sleep(m_secs)
    print(f'endpoint:{endpoint_req}')
    declarantes_json = requests.get(endpoint_req).json()
    
    if len(declarantes_json) > 0:
        df = pd.DataFrame(declarantes_json)
        df['genre'] = a_genre
        df['political_party'] = a_political_party
        ls_genre_party.append(df)
    
df_total = pd.concat(ls_genre_party)
df_total



[['M' '1' 'PRI']
 ['M' '2' 'PRI']
 ['M' '3' 'PRI']
 ['M' '4' 'PRI']
 ['F' '1' 'PRI']
 ['F' '2' 'PRI']
 ['F' '3' 'PRI']
 ['F' '4' 'PRI']]
endpoint:https://3de3.mx/declarantes.json?page=1&by_gender=M&by_political_party=PRI
endpoint:https://3de3.mx/declarantes.json?page=2&by_gender=M&by_political_party=PRI
endpoint:https://3de3.mx/declarantes.json?page=3&by_gender=M&by_political_party=PRI
endpoint:https://3de3.mx/declarantes.json?page=4&by_gender=M&by_political_party=PRI
endpoint:https://3de3.mx/declarantes.json?page=1&by_gender=F&by_political_party=PRI
endpoint:https://3de3.mx/declarantes.json?page=2&by_gender=F&by_political_party=PRI
endpoint:https://3de3.mx/declarantes.json?page=3&by_gender=F&by_political_party=PRI
endpoint:https://3de3.mx/declarantes.json?page=4&by_gender=F&by_political_party=PRI


id         first_name         last_name          twitter  \
0    177       Miguel Ángel    Riquelme Solís         mrikelme   
1    178       José Ignacio   Peralta Sánchez  nachoperaltacol   
2    182             Héctor  Astudillo Flores  HectorAstudillo   
3    183               Omar     Fayad Meneses        omarfayad   
4    185            Alfredo     Del Mazo Maza   alfredodelmazo   
..   ...                ...               ...              ...   
26   553        María Elena  Verduzco Chaires   gobiernosonora   
27   554            Brianda   Vivian Martínez   bVivianOficial   
28   537    Karina Teresita      Zárate Félix    KarinaZarateF   
29   606     María Maricela   Escobar Sánchez      GobTlaxcala   
30  6997  María del Rosario  Sánchez Olivares      charolizate   

                              position  \
0                           Gobernador   
1                           Gobernador   
2                           Gobernador   
3                           Gobernador   
4                           Gobernador   
..                                 ...   
26                        Radio Sonora   
27  Instituto Sonorense de la Juventud   
28       Directora de DIF Sonora y FES   
29            Contralora del Ejecutivo   
30                                None   

                                            interests  \
0   {'document_link': 'https://s3-us-west-1.amazon...   
1   {'document_link': 'https://s3-us-west-1.amazon...   
2   {'document_link': 'https://s3-us-west-1.amazon...   
3   {'document_link': 'https://s3-us-west-1.amazon...   
4   {'document_link': 'https://s3-us-west-1.amazon...   
..                                                ...   
26  {'document_link': 'https://s3-us-west-1.amazon...   
27  {'document_link': 'https://s3-us-west-1.amazon...   
28  {'document_link': 'https://s3-us-west-1.amazon...   
29  {'document_link': 'https://s3-us-west-1.amazon...   
30  {'document_link': 'https://s3-us-west-1.amazon...   

                                            ownership  \
0   {'document_link': 'https://s3-us-west-1.amazon...   
1   {'document_link': 'https://s3-us-west-1.amazon...   
2   {'document_link': 'https://s3-us-west-1.amazon...   
3   {'document_link': 'https://s3-us-west-1.amazon...   
4   {'document_link': 'https://s3-us-west-1.amazon...   
..                                                ...   
26  {'document_link': 'https://s3-us-west-1.amazon...   
27  {'document_link': 'https://s3-us-west-1.amazon...   
28  {'document_link': 'https://s3-us-west-1.amazon...   
29  {'document_link': 'https://s3-us-west-1.amazon...   
30  {'document_link': 'https://s3-us-west-1.amazon...   

                                               fiscal genre political_party  
0   {'document_link': 'https://s3-us-west-1.amazon...     M             PRI  
1   {'document_link': 'https://s3-us-west-1.amazon...     M             PRI  
2   {'document_link': 'https://s3-us-west-1.amazon...     M             PRI  
3   {'document_link': 'https://s3-us-west-1.amazon...     M             PRI  
4   {'document_link': 'https://s3-us-west-1.amazon...     M             PRI  
..                                                ...   ...             ...  
26  {'document_link': 'https://s3-us-west-1.amazon...     F             PRI  
27  {'document_link': 'https://s3-us-west-1.amazon...     F             PRI  
28  {'document_link': 'https://s3-us-west-1.amazon...     F             PRI  
29  {'document_link': 'https://s3-us-west-1.amazon...     F             PRI  
30  {'document_link': 'https://s3-us-west-1.amazon...     F             PRI  

[206 rows x 10 columns]

In [284]:
df_total

Empty DataFrame
Columns: []
Index: []

In [ ]:
# Número total funcionarios en #3de3

In [ ]:
# Participación en #3de3 por género

In [ ]:
# Numero de funcionarios por partido

Iniciativa 3de3

# 5. Retos (opcional)

- Random Walk

- Game of Life

- Imagenes

- Texto

# 6. Conclusiones
- ¿Qué se llevan de esta semana?
- ¿Qué áreas encontraron de oportunidad en ustedes?
- ¿Qué les hubiera gustado ver en esta semana?